### ISSUE TITLE
disparity_samples.py

### ISSUE THREAD

**Issue by huohuohuohuohuohuohuohuo** [PlenopticToolbox/PlenopticToolbox2.0#4]
When I run the disparity_samples.py ,it give a error as follows:
$ python3 disparity_sample.py Camera_Processed.xml -dmin 0 -dmax 10 -err False -scene 'real'
Traceback (most recent call last):
  File "disparity_sample.py", line 50, in <module>
    I, disp, Dwta, Dgt, Dconf, Dcoarse, disparities, ncomp, disp_avg, new_offset, error_measurements = rtxmain.estimate_disp(params)
  File "/home/jdy/Huoxiao/toolbox2.0/PlenopticToolbox2.0-master/python/samples/disparity/disparity_methods.py", line 35, in estimate_disp
    lenses = rtxIO.load_scene(args.filename, args.analyze_err)
  File "/home/jdy/Huoxiao/toolbox2.0/PlenopticToolbox2.0-master/python/samples/plenopticIO/imgIO.py", line 161, in load_scene
    lenses = load_with_disp(img_filename, disp_name, filename)
  File "/home/jdy/Huoxiao/toolbox2.0/PlenopticToolbox2.0-master/python/samples/plenopticIO/imgIO.py", line 207, in load_with_disp
    disp_interp = sinterp.RectBivariateSpline(gridy, gridx, disp_data)
  File "/home/jdy/.pyenv/versions/3.7.0/lib/python3.7/site-packages/scipy/interpolate/fitpack2.py", line 1168, in __init__
    raise ValueError('x dimension of z must have same number of '
ValueError: x dimension of z must have same number of elements as x

And how can I fix this error?
Thank you so much.

**Comment by huoxiaodaren** [comment]
It seems like the statement of disp_interp = sinterp.RectBivariateSpline(gridy, gridx, disp_data) have some 
problems ,so I print the length of gridy and disp_data[0],it turns out they are the same as width(pixel) of Camera_Processed.png and Camera_Processed_disp.png.So I change the width and hight of the two pictures to be same.Finally I run the refocused_img.py successfully,but the output img is more terrible than the refoused_img in the google folder dataset.Then I run the  disparity_samples.py and it has been running for a long time without stopping.How can I fix this?
PLEASE CONTACT ME!THANK YOU!

**Comment by PlenopticToolbox** [comment]
Hello,
as in the other issue, if needed send me an e-mail and we can discuss more in details: lpa@informatik.uni-kiel.de.

There was a small bug on the parameters -err. If you didn't give anything, he would take automatic False (at least he was in the previous version) but if you would give him False he would read it as a string and then the if was bad written (if calc_err) and calc_err was 'False' so it existed somehow and it took it as True.
I fixed it, it should work normally.

About the refocused image, it depends a lot from the parameters, the image that you are using, the disparity that you calculated (you used dmax 10, there may be bigger). And also the one in google folder is using Raytrix software, that involved post-processing (filtering, smoothing, I don't know exactly because it is not open-source). It is always a big discussion on how to get such images (refocused) and there are many ways. the one used here (using patches) is probably not the best one for quality, it was for now the easiest as a demonstration, but I agree that sometimes it is not the best quality. I am also working on something better, but it's not ready yet. If you are interesting in collaborating or doing your own script to go from disparity per lens to disparity using a different approach (going to 3D world and back-projecting for example) that would be nice, among other things I had no time to do it, sooner or later I think it will be available.
